export const HOME_ACTION_TYPE = {
  HOME_UPLOAD_PENDING: 'HOME_ACTION_TYPE.HOME_UPLOAD_PENDING',
  HOME_UPLOAD_SUCCESS: 'HOME_ACTION_TYPE.HOME_UPLOAD_SUCCESS',
  HOME_UPLOAD_ERROR: 'HOME_ACTION_TYPE.HOME_UPLOAD_ERROR',
};

export const USER_DATA_NAME = {
  //USERS: 'users',
  ID: 'id',
  LOGIN: 'login',
};
